# Generated by Django 3.2.9 on 2021-12-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_notificationstaffs_notificationstudent_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestermodel',
            name='name',
            field=models.CharField(default='Spring', max_length=20),
        ),
        migrations.AddField(
            model_name='staffs',
            name='email',
            field=models.EmailField(default='Spring', max_length=254),
            preserve_default=False,
        ),
    ]
