# Generated by Django 4.0 on 2022-01-02 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_alter_notice_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='file',
        ),
    ]
